# Stage 1: build
FROM node:18-alpine AS build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY package.json package-lock.json ./
COPY public ./public
COPY src ./src

ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=http://localhost:8081/api

RUN npm ci --silent
RUN npm run build

# Stage 2: serve with nginx
FROM nginx:1.25-alpine
COPY --from=build /app/build /usr/share/nginx/html

# your custom nginx config (optional)
# COPY nginx.conf /etc/nginx/conf.d/default.conf   <-- comment or remove this line

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
