package com.luxestore.model;

import jakarta.persistence.*;
import lombok.*;
import java.util.Date;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "orders")
public class OrderEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private Long userId;
    private Date orderDate;
    private double total;
    @Lob
    private String itemsJson; // JSON string of items

    public OrderEntity(Long userId, Date orderDate, double total, String itemsJson) {
        this.userId = userId;
        this.orderDate = orderDate;
        this.total = total;
        this.itemsJson = itemsJson;
    }
    //getters and setters are generated by Lombok

    public Long getId() {
        return id;
    }

    public Long getUserId() {
        return userId;
    }

    public Date getOrderDate() {
        return orderDate;
    }

    public double getTotal() {
        return total;
    }

    public String getItemsJson() {
        return itemsJson;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    public void setTotal(double total) {
        this.total = total;
    }

    public void setItemsJson(String itemsJson) {
        this.itemsJson = itemsJson;
    }

}
